# Generated by Django 3.1.7 on 2022-07-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='url',
        ),
    ]
