# Generated by Django 3.2.16 on 2024-07-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_attachments_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='page_files/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='wiki.page')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]